### ISSUE TITLE
Som en CategoryProvider vill jag kunna skapa en category

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_CategoryProvider#2]
![Image](https://github.com/user-attachments/assets/dae6e384-eaf1-4ee4-945e-53dac3098cfd)

### **Acceptanskriterier:**

1. Kunna skapa en ny kategori om den inte existerar.
2. Om kategorin existerar så läggs produkten till i rätt kategori.

### **Tasks:**
- [x] Skapa en funktion "CreateCategory" som hanterar skapandet av en kategori

- [x] Validera inkommande request, retunera 400 om valideringen misslyckas 

- [x] Implementera databasinteraktion för att spara kategorin och returnera resultatet

>### **Testfallsbeskrivning:**

>Testfall 1: 

Kategori skapas.

Förutsättningar: Produkt läggs till som inte redan har en existerande kategori.

>Steg: 
1. Produkt läggs till.
2. Kategorin som produkten har läggs till existerande inte.
3. Produkten skapas.

>### **Förväntat resultat:**
Kategorin skapas.

>Testfall 2:

Kategori skapas inte.

Förutsättningar: Produkt läggs till och har redan har en existerande kategori.

>Steg: 
1. Produkt läggs till.
2. Kategorin som produkten har existerar redan.

>### **Förväntat resultat:**
Kategorin skapas inte och produkten läggs till i existerande kategori.

>Testfall 3: 

Kategori misslyckas att skapas.
Förutsättningar: Produkt läggs till som inte redan har en existerande kategori.

>Steg: 

1. Produkt läggs till.
2. Produktens kategori existerar inte.

>### **Förväntat resultat:**
Kategorin misslyckas att skapas, 400 kod.
